package com.ws.tutorial.ws_example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-26T21:07:16.980-07:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CalcServiceService", 
                  wsdlLocation = "http://localhost:8080/ws-example-0.0.1-SNAPSHOT/services/calc?wsdl",
                  targetNamespace = "http://ws_example.tutorial.ws.com/") 
public class CalcServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws_example.tutorial.ws.com/", "CalcServiceService");
    public final static QName CalcServicePort = new QName("http://ws_example.tutorial.ws.com/", "CalcServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-example-0.0.1-SNAPSHOT/services/calc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalcServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-example-0.0.1-SNAPSHOT/services/calc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalcServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalcServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalcServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalcServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalcServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CalcService
     */
    @WebEndpoint(name = "CalcServicePort")
    public CalcService getCalcServicePort() {
        return super.getPort(CalcServicePort, CalcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcService
     */
    @WebEndpoint(name = "CalcServicePort")
    public CalcService getCalcServicePort(WebServiceFeature... features) {
        return super.getPort(CalcServicePort, CalcService.class, features);
    }

}
