package com.ws.tutorial.ws_example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-26T21:07:16.870-07:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ws_example.tutorial.ws.com/", name = "CalcService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalcService {

    @WebMethod
    @RequestWrapper(localName = "getDiff", targetNamespace = "http://ws_example.tutorial.ws.com/", className = "com.ws.tutorial.ws_example.GetDiff")
    @ResponseWrapper(localName = "getDiffResponse", targetNamespace = "http://ws_example.tutorial.ws.com/", className = "com.ws.tutorial.ws_example.GetDiffResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getDiff(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getSum", targetNamespace = "http://ws_example.tutorial.ws.com/", className = "com.ws.tutorial.ws_example.GetSum")
    @ResponseWrapper(localName = "getSumResponse", targetNamespace = "http://ws_example.tutorial.ws.com/", className = "com.ws.tutorial.ws_example.GetSumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getSum(
        @WebParam(name = "first", targetNamespace = "")
        int first,
        @WebParam(name = "second", targetNamespace = "")
        int second
    );
}
